from setuptools import setup,find_packages

setup(
    name='ml_draftpick_dss',
    version='0.1.0',    
    description='ML Draftpick DSS',
    url='https://github.com/R-N/ml_draftpick_dss',
    author='Muhammad Rizqi Nur',
    author_email='rizqinur2010@gmail.com',
    license='MIT License',
    packages=find_packages(),
    install_requires=[
        'pandas',
        'numpy==1.26.4', 
        'tensorflow',
        'tensorflow-addons',
        'paddleocr',
        'paddlepaddle',
        'thefuzz',
        'requests-html',
        'torch',
        'opencv-python',
        'scikit-image',
        'albumentations==1.4.10',
        'plotly',
        'torchinfo',
        'optuna',
        'scipy',
        'torch-lr-finder',
        'catboost',
        'coloredlogs',
        'tqdm',
        'albucore==0.0.13',
        'protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3'
    ],

    classifiers=[
        'Development Status :: 1 - Planning',
        'Intended Audience :: Science/Research',
        'License :: MIT License',  
        'Operating System :: POSIX :: Linux',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.9',
    ],
)